# ────────────────────────────────────────────────
# Stage 1: Builder — install deps, generate Prisma, build app
# ────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

# 1. Copy manifests first (better caching)
COPY package.json package-lock.json ./

# 2. Install ALL dependencies (including dev)
RUN npm ci --legacy-peer-deps

# 3. Copy full source code
COPY . .

# 4. Generate Prisma client INSIDE container
RUN npx prisma generate

# 5. Build both client + server
RUN npm run build


# ────────────────────────────────────────────────
# Stage 2: Production image — minimal runtime
# ────────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

# 1. Copy package manifest and install ONLY production deps
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --legacy-peer-deps

# 2. Copy built files from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public

# 3. Copy Prisma client generated by "prisma generate"
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# 4. Port for your SSR server
EXPOSE 3000

# 5. Run server
CMD ["npm", "start"]
