import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import { ApiResponse } from "@/types";
import { tmdbClient } from "@/lib/tmdb";

// ---------------------------------------------
// Validation schema
// ---------------------------------------------
const SearchSchema = z.object({
  q: z.string().optional(),
  limit: z.string().transform(Number).optional().default("50"),
  offset: z.string().transform(Number).optional().default("0"),
  page: z.string().transform(Number).optional().default("1"),
});

// Helper function to convert TMDB movie to local format
function mapTMDBMovieToLocal(tmdbMovie: any) {
  return {
    id: undefined, // Will be generated by DB
    tmdbId: tmdbMovie.id,
    title: tmdbMovie.title,
    year: new Date(tmdbMovie.release_date || '2024-01-01').getFullYear(),
    genres: tmdbMovie.genre_ids || [],
    platform: null,
    poster: tmdbMovie.poster_path ? `https://image.tmdb.org/t/p/w500${tmdbMovie.poster_path}` : null,
    description: tmdbMovie.overview || '',
    imdbRating: tmdbMovie.vote_average || null,
    rtRating: null,
    releaseDate: tmdbMovie.release_date ? new Date(tmdbMovie.release_date) : null,
  };
}

// ---------------------------------------------
// GET /api/movies
// ---------------------------------------------
export async function GET(req: NextRequest) {
  try {
    const searchParams = req.nextUrl.searchParams;

    const parsed = SearchSchema.safeParse({
      q: searchParams.get("q"),
      limit: searchParams.get("limit"),
      offset: searchParams.get("offset"),
      page: searchParams.get("page"),
    });

    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: "Invalid query parameters" },
        { status: 400 }
      );
    }

    const { q, limit, offset, page } = parsed.data;

    // If TMDB API is available, prefer it for searches
    if (q && process.env.TMDB_API_KEY) {
      const tmdbResponse = await tmdbClient.searchMovies(q, page);
      
      if (tmdbResponse) {
        // Map TMDB results to local format
        const mappedMovies = tmdbResponse.results.map(mapTMDBMovieToLocal);
        
        return NextResponse.json({
          success: true,
          data: mappedMovies,
          pagination: {
            page: tmdbResponse.page,
            totalPages: tmdbResponse.total_pages,
            totalResults: tmdbResponse.total_results,
          },
        });
      }
    }

    // Fallback to local database
    const whereClause: Prisma.MovieWhereInput = q
      ? {
          OR: [
            { title: { contains: q, mode: Prisma.QueryMode.insensitive } },
            { description: { contains: q, mode: Prisma.QueryMode.insensitive } },
            { genres: { has: q } },
          ],
        }
      : {};

    const movies = await prisma.movie.findMany({
      where: whereClause,
      orderBy: { createdAt: "desc" },
      skip: offset,
      take: limit,
    });

    const total = await prisma.movie.count({ where: whereClause });

    return NextResponse.json({
      success: true,
      data: movies,
      pagination: {
        offset,
        limit,
        total,
      },
    });
  } catch (err) {
    console.error("Get movies error:", err);
    return NextResponse.json(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
